name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install .NET 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build, Test, Pack, Publish
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        dotnet tool install -g dotnet-releaser --configfile .github/workflows/nuget_org_only.config
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" src/dotnet-releaser.toml

    - name: Build, Test
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        dotnet tool install -g dotnet-releaser --configfile .github/workflows/nuget_org_only.config
        dotnet-releaser build src/dotnet-releaser.toml